### ISSUE TITLE
When clicked on leave  meet - there should be a confirmation (OK or Cancel) 

### ISSUE THREAD

**Issue by nigdifg** [Ayanabha1/MeetUp#20]
As many times if by accident leave button clicked then - Meet will be end , which is not good.

I can fix this issue , assign to me.

**Comment by Ayanabha1** [comment]
Thanks for your contribution :)
The changes are now active in the production environment.
![image](https://github.com/Ayanabha1/MeetUp/assets/63809278/9824ccd2-fa05-4f9b-92d3-7d03beb04cae)

**Comment by nigdifg** [comment]
Thanks for accepting my contribution and for adding me in the contributor list , hope will add some more features and make this project more advanced.

**Comment by Ayanabha1** [comment]
Looking forward to that :)
